apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: petclinic-ns
  name: petclinic
spec:
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: petclinic
        image: 104785239205.dkr.ecr.us-east-2.amazonaws.com/k8s-petclinic-sj:number
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
