apiVersion: v1
kind: Service
metadata:
  name: petclinic-svc
  namespace: petclinic-ns
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: alb
spec:
  selector:
    app: petclinic
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer